Album Template and Page Routing
JacobHearst/spotify-playlist-plus pull request #7
Opened 2021-02-15 21:13 UTC by MattKlas

Add page routing and basic page setup for albums.

2021-02-15 21:27 UTC, JacobHearst requested changes

2021-02-15 21:27 UTC, JacobHearst commented on .eslintrc.json
> +    "parser": "babel-eslint",
Your build is failing because of this, does it need to be added to the project's dev dependencies?

2021-02-16 18:14 UTC, MattKlas commented
Got it working now, can merge whenever.

2021-02-16 19:47 UTC, JacobHearst approved these changes

2021-02-16 19:48 UTC, merged